#!/usr/bin/env python

import sys 

fh = open(sys.argv[1])

string = "DROME"

ct = 0

for line in fh:
    if string in line:
        fields = line.rstrip("\r\n").split()
        if len(fields)!=4:
            continue
        ct += 1
        if ct > 100:
            break
        gene_name1 = fields[2]
        gene_name2 = fields[3]
        
            
        print gene_name2, gene_name1
